按需引入这个组件会提示tag和price引入失败
jdf2e/nutui pull request #1420
Opened 2022-06-24 09:06 UTC by zhangzheng7856

按需引入这个组件会提示tag和price未引入。。

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [X] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] NutUI 2.0
- [X] NutUI 3.0 H5
- [ ] NutUI 3.0 小程序

**这个 PR 是否已自测:**

- [X ] 自测 vue3 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vue3)
- [ ] 自测 vite 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vite-ts)
- [ ] 自测 taro 脚手架使用小程序 & h5 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/taro)

2022-07-01 06:49 UTC, richard1015 requested changes
文档更新一下即可

```
import { createApp } from 'vue';
// vue
import { Card,Tag,Price} from '@nutui/nutui';
// taro
import { Card ,Tag,Price} from '@nutui/nutui-taro';

const app = createApp();
app.use(Card).use(Tag).use(Price);
```

2022-07-01 07:23 UTC, zhangzheng7856 commented
不好意思，我没描述清楚，按需引入Card 商品卡片的时候，会报警提示tag和price引入失败，是Card组件直接没有按需引入

2022-07-01 07:25 UTC, zhangzheng7856 commented
我这个PR 提交文件更改的也是 src/packages/__VUE/card/index.vue，只是觉得案例说引入card组件然后报tag和price 未引入挺唐突的

2022-07-07 07:08 UTC, Drjingfubo commented
你这样引入的意义在哪儿呢，你在使用组件的时候按需加载引入tag和price组件了吗？

2022-07-07 07:12 UTC, closed without merging

2022-07-11 07:13 UTC, zhangzheng7856 commented
> 你这样引入的意义在哪儿呢，你在使用组件的时候按需加载引入tag和price组件了吗？

没啥好讲的，很棒👍🏻，感谢开源