chore(audio): use icons-vue component
jdf2e/nutui pull request #1930
Opened 2022-12-14 11:50 UTC by gyt95

**这个 PR 做了什么?** (简要描述所做更改)

 Audio 组件中使用 icons-vue

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [x] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] NutUI 2.0
- [-] NutUI 3.0 H5
- [ ] NutUI 3.0 小程序

**这个 PR 是否已自测:**

- [ ] 自测 vue3 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vue3-vue-cli)
- [ ] 自测 vite 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vite-ts)
- [ ] 自测 taro 脚手架使用小程序 & h5 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/taro)

2022-12-15 11:21 UTC, gyt95 commented
![1671103245719](https://user-images.githubusercontent.com/23090676/207846653-39119eeb-8467-4f80-8e21-0f1be1fc4e7e.png)

2022-12-15 11:23 UTC, gyt95 commented
“基本用法“里它的box-shadow样式自己变了，但代码没改过。试过把相关的类名例如nut-audio__icon--box改为nut-audio-icon-box也不行

2022-12-16 01:34 UTC, richard1015 requested changes

2022-12-16 01:34 UTC, richard1015 commented on package.json
> +    "@nutui/icons-vue": "0.0.9",
此文件无需提交

2022-12-16 01:34 UTC, richard1015 commented on pnpm-lock.yaml
> +  '@nutui/icons-vue': 0.0.9
此文件无需提交，以父仓库为主

2022-12-16 01:34 UTC, richard1015 commented on src/packages/__VUE/audio/demo.vue
> +      console.log('改变进度条', val, audioDemo.value);
此处为啥多了一个audioDemo.value

2022-12-16 01:49 UTC, gyt95 commented on pnpm-lock.yaml
> +  '@nutui/icons-vue': 0.0.9
好的

2022-12-16 01:50 UTC, gyt95 commented on package.json
> +    "@nutui/icons-vue": "0.0.9",
好的已恢复

2022-12-16 08:42 UTC, richard1015 approved these changes

2022-12-16 08:42 UTC, merged