chore(image): use icons-vue component
jdf2e/nutui pull request #1940
Opened 2022-12-15 14:58 UTC by xiaosifeng

**这个 PR 做了什么?** (简要描述所做更改)

image组件 中使用了 icons-vue

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [x] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] NutUI 2.0
- [ ] NutUI 3.0 H5
- [ ] NutUI 3.0 小程序

**这个 PR 是否已自测:**

- [ ] 自测 vue3 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vue3-vue-cli)
- [ ] 自测 vite 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vite-ts)
- [ ] 自测 taro 脚手架使用小程序 & h5 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/taro)

2022-12-15 15:00 UTC, xiaosifeng commented
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/49484460/207893738-26d7424b-f98d-443a-9f27-844cc4d28fde.png">

2022-12-16 00:49 UTC, richard1015 requested changes
添加name属性

2022-12-16 00:49 UTC, richard1015 commented on src/packages/__VUE/image/demo.vue
> +              <Loading width="16px" height="16px"></Loading>
缺少 name 属性
```<Loading width="16px" height="16px" name="loading"></Loading>```

2022-12-16 00:49 UTC, richard1015 commented on src/packages/__VUE/image/demo.vue
> +              <CircleClose width="16px" height="16px"></CircleClose>
添加name属性

2022-12-16 00:49 UTC, richard1015 commented on src/packages/__VUE/image/index.vue
> -      <nut-icon name="image" v-if="!slotLoding"></nut-icon>
添加name属性

2022-12-16 00:49 UTC, richard1015 commented on src/packages/__VUE/image/index.vue
> -      <nut-icon name="image-error" v-if="!slotError"></nut-icon>
添加name属性

2022-12-16 10:30 UTC, merged