feat: noticebar icon 更换,文档修改
jdf2e/nutui pull request #1957
Opened 2022-12-20 10:36 UTC by Ymm0008

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] NutUI 2.0
- [ ] NutUI 3.0 H5
- [ ] NutUI 3.0 小程序

**这个 PR 是否已自测:**

- [ ] 自测 vue3 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vue3-vue-cli)
- [ ] 自测 vite 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vite-ts)
- [ ] 自测 taro 脚手架使用小程序 & h5 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/taro)

2022-12-21 09:13 UTC, richard1015 requested changes

2022-12-21 09:13 UTC, richard1015 commented on src/packages/__VUE/noticebar/demo.vue
> +    <nut-noticebar :closeMode="true" @click="hello">{{ translate('text') }} </nut-noticebar>
closeMode改
close-mode

2022-12-21 09:13 UTC, richard1015 commented on src/packages/__VUE/noticebar/index.taro.vue
> +          <!-- <nut-icon type="cross" :color="color" size="11px"></nut-icon> -->
注释直接删除

2022-12-21 09:13 UTC, richard1015 commented on src/packages/__VUE/searchbar/doc.en-US.md
> +import { Searchbar } from '@nutui/nutui-taro';
删除掉 @nutui/nutui-taro

2022-12-21 09:13 UTC, richard1015 commented on src/packages/__VUE/searchbar/index.vue
> +    console.log(slots);
日志删除

2022-12-21 09:13 UTC, richard1015 commented on src/sites/mobile-taro/vue/src/exhibition/pages/noticebar/index.vue
> +    <nut-noticebar :closeMode="true" @click="hello" :background="`rgba(251, 248, 220, 1)`" :color="`#D9500B`"
close-mode

2022-12-21 13:27 UTC, Ymm0008 commented on src/sites/mobile-taro/vue/src/exhibition/pages/noticebar/index.vue
> +    <nut-noticebar :closeMode="true" @click="hello" :background="`rgba(251, 248, 220, 1)`" :color="`#D9500B`"
已修改

2022-12-22 06:37 UTC, richard1015 approved these changes

2022-12-22 06:38 UTC, merged