docs: tabs数量多,滚动操作 doc 更新
jdf2e/nutui pull request #2158
Opened 2023-03-05 01:47 UTC by xxweb123

**这个 PR 做了什么?** (简要描述所做更改)

**这个 PR 是什么类型?** (至少选择一个)

- [ ] 错误修复(Bugfix) issue id #
- [ ] 新功能(Feature)
- [ ] 代码重构(Refactor)
- [ ] TypeScript 类型定义修改(Typings)
- [ ] 文档修改(Docs)
- [ ] 代码风格更新(Code style update)
- [ ] 其他，请描述(Other, please describe):

**这个 PR 涉及以下平台:**

- [ ] NutUI 2.0
- [ ] NutUI 3.0 H5
- [ ] NutUI 3.0 小程序
- [ ] NutUI 4.0 H5
- [ ] NutUI 4.0 小程序

**这个 PR 是否已自测:**

- [ ] 自测 vue3 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vue3-vue-cli)
- [ ] 自测 vite 脚手架使用 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/vite-ts)
- [ ] 自测 taro 脚手架使用小程序 & h5 [测试仓库](https://github.com/jdf2e/nutui-demo/tree/master/taro)

2023-03-06 15:57 UTC, gyt95 requested changes
建议只改 <script> 里的名称，把 tab1value 改为 tab4value ，和 list4 对应。

2023-03-09 03:49 UTC, xxweb123 commented
ok

2023-03-09 03:58 UTC, xxweb123 commented
已经从新修改完成

2023-03-09 04:01 UTC, xxweb123 commented
> 建议只修改 <script> 里的名称，把 tab1value 修改为 tab4value ，和 list4 对应。
ok, 已经从新修改完成

2023-03-09 06:11 UTC, gyt95 approved these changes

2023-03-09 06:58 UTC, richard1015 approved these changes

2023-03-09 06:58 UTC, merged